/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.mushroomhunter.restclient;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import cz.fi.muni.pa165.mushroomhunter.api.dto.LocationDto;
import cz.fi.muni.pa165.mushroomhunter.api.dto.MushroomDto;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author Lukáš Valach
 */
public class RestClient extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public RestClient() {
        initComponents();

        allLocationsSwingWorker = new AllLocationsSwingWorker();
        allLocationsSwingWorker.execute();

        allMushroomsSwingWorker = new AllMushroomsSwingWorker();
        allMushroomsSwingWorker.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMushroom = new javax.swing.JTable();
        bMushroomDelete = new javax.swing.JButton();
        bMushroomUpdate = new javax.swing.JButton();
        bMushroomCreate = new javax.swing.JButton();
        tfMushroomName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lMessageMushrooms = new javax.swing.JLabel();
        comboBoxMushroomStartOfOccurence = new javax.swing.JComboBox();
        comboBoxMushroomEndOfOccurence = new javax.swing.JComboBox();
        comboBoxMushroomType = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocation = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfLocationName = new javax.swing.JTextField();
        tfLocationDescription = new javax.swing.JTextField();
        tfLocationNearCity = new javax.swing.JTextField();
        bLocationCreate = new javax.swing.JButton();
        bLocationUpdate = new javax.swing.JButton();
        bLocationDelete = new javax.swing.JButton();
        lMessageLocations = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMushroom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Start of occurence", "End of occurence"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMushroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMushroomMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMushroom);

        bMushroomDelete.setText("Delete mushroom");
        bMushroomDelete.setEnabled(false);
        bMushroomDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMushroomDeleteActionPerformed(evt);
            }
        });

        bMushroomUpdate.setText("Update mushroom");
        bMushroomUpdate.setEnabled(false);
        bMushroomUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMushroomUpdateActionPerformed(evt);
            }
        });

        bMushroomCreate.setText("Create mushroom");
        bMushroomCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMushroomCreateActionPerformed(evt);
            }
        });

        tfMushroomName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMushroomNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jLabel5.setText("Type");

        jLabel6.setText("Start of occurence");

        jLabel8.setText("End of occurence");

        lMessageMushrooms.setForeground(java.awt.Color.red);

        comboBoxMushroomStartOfOccurence.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--choose month--", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        comboBoxMushroomEndOfOccurence.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--choose month--", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        comboBoxMushroomType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--choose type--", "EDIBLE", "INEDIBLE", "POISONOUS" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bMushroomCreate)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bMushroomUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bMushroomDelete))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxMushroomEndOfOccurence, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfMushroomName)
                                    .addComponent(comboBoxMushroomStartOfOccurence, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxMushroomType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(340, 340, 340))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMessageMushrooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfMushroomName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxMushroomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxMushroomStartOfOccurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboBoxMushroomEndOfOccurence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMushroomUpdate)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bMushroomCreate)
                        .addComponent(bMushroomDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lMessageMushrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage mushrooms", jPanel1);

        tblLocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Near city"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLocationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLocation);

        jLabel1.setText("Name");

        jLabel2.setText("Description");

        jLabel3.setText("Near city");

        tfLocationName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLocationNameActionPerformed(evt);
            }
        });

        bLocationCreate.setText("Create location");
        bLocationCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLocationCreateActionPerformed(evt);
            }
        });

        bLocationUpdate.setText("Update location");
        bLocationUpdate.setEnabled(false);
        bLocationUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLocationUpdateActionPerformed(evt);
            }
        });

        bLocationDelete.setText("Delete location");
        bLocationDelete.setEnabled(false);
        bLocationDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLocationDeleteActionPerformed(evt);
            }
        });

        lMessageLocations.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfLocationNearCity)
                                    .addComponent(tfLocationDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(tfLocationName)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(bLocationCreate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bLocationUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bLocationDelete)))
                        .addGap(0, 366, Short.MAX_VALUE))
                    .addComponent(lMessageLocations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfLocationDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfLocationNearCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLocationCreate)
                    .addComponent(bLocationDelete)
                    .addComponent(bLocationUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lMessageLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage locations", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLocationCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLocationCreateActionPerformed
        lMessageLocations.setText("");
        DefaultTableModel model = (DefaultTableModel) tblLocation.getModel();
        if (tfLocationName.getText().trim().equals("")) {
            lMessageLocations.setText("Location name cannot be empty.");
            return;
        }
        if (tfLocationName.getText().trim().length() > 20) {
            lMessageLocations.setText("Location cannot be longer than 20 characters.");
            return;
        }
        if (tfLocationDescription.getText().trim().length() > 20) {
            lMessageLocations.setText("Location cannot be longer than 200 characters.");
            return;
        }
        if (tfLocationNearCity.getText().trim().length() > 20) {
            lMessageLocations.setText("Location cannot be longer than 20 characters.");
            return;
        }
        locationCreateSwingWorker = new LocationCreateSwingWorker();
        locationCreateSwingWorker.execute();
    }//GEN-LAST:event_bLocationCreateActionPerformed

    private void bLocationUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLocationUpdateActionPerformed
        lMessageLocations.setText("");
        
        if (tfLocationName.getText().trim().equals("")) {
            lMessageLocations.setText("Location name cannot be empty.");
            return;
        }
        if (tfLocationName.getText().trim().length() > 20) {
            lMessageLocations.setText("Location cannot be longer than 20 characters.");
            return;
        }
        if (tfLocationDescription.getText().trim().length() > 20) {
            lMessageLocations.setText("Location cannot be longer than 200 characters.");
            return;
        }
        if (tfLocationNearCity.getText().trim().length() > 20) {
            lMessageLocations.setText("Location cannot be longer than 20 characters.");
            return;
        }
        
        if (tblLocation.getSelectedRow() == -1) {
            if (tblLocation.getRowCount() == 0) {
                lMessageLocations.setText("There are no locations to be updated.");
            } else {
                lMessageLocations.setText("Please select single location.");
            }
        } else {
            locationUpdateSwingWorker = new LocationUpdateSwingWorker();
            locationUpdateSwingWorker.execute();
        }
    }//GEN-LAST:event_bLocationUpdateActionPerformed

    private void bLocationDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLocationDeleteActionPerformed
        bLocationDelete.setEnabled(false);
        bLocationUpdate.setEnabled(false);

        //lMessage.setText(texts.getString("errTableEmpty"));
        if (tblLocation.getSelectedRow() == -1) {
            if (tblLocation.getRowCount() == 0) {
                lMessageLocations.setText("There are no locations to be deleted.");
            } else {
                lMessageLocations.setText("Please select single location.");
            }
        } else {
            locationDeleteSwingWorker = new LocationDeleteSwingWorker();
            locationDeleteSwingWorker.execute();
        }
    }//GEN-LAST:event_bLocationDeleteActionPerformed

    private void tfLocationNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLocationNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLocationNameActionPerformed


    private void tblLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLocationMouseClicked
        bLocationDelete.setEnabled(true);
        bLocationUpdate.setEnabled(true);

        DefaultTableModel model = (DefaultTableModel) tblLocation.getModel();
        tfLocationName.setText(model.getValueAt(tblLocation.getSelectedRow(), 0).toString());
        tfLocationDescription.setText(model.getValueAt(tblLocation.getSelectedRow(), 1).toString());
        tfLocationNearCity.setText(model.getValueAt(tblLocation.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tblLocationMouseClicked

    private void tfMushroomNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMushroomNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMushroomNameActionPerformed

    private void bMushroomCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMushroomCreateActionPerformed
        lMessageMushrooms.setText("");
        if (tfMushroomName.getText().trim().equals("")) {
            lMessageMushrooms.setText("Mushroom name cannot be empty.");
            return;
        }
        if (comboBoxMushroomType.getSelectedItem().equals("--choose type--")) {
            lMessageMushrooms.setText("Mushroom type cannot be empty.");
            return;
        }
        if (comboBoxMushroomStartOfOccurence.getSelectedItem().equals("--choose month--")) {
            lMessageMushrooms.setText("Mushroom start of occurence cannot be empty.");
            return;
        }
        if (comboBoxMushroomEndOfOccurence.getSelectedItem().equals("--choose month--")) {
            lMessageMushrooms.setText("Mushroom end of occurence cannot be empty.");
            return;
        }
        mushroomCreateSwingWorker = new MushroomCreateSwingWorker();
        mushroomCreateSwingWorker.execute();
    }//GEN-LAST:event_bMushroomCreateActionPerformed

    private void bMushroomUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMushroomUpdateActionPerformed
        lMessageMushrooms.setText("");
        
        if (tfMushroomName.getText().trim().equals("")) {
            lMessageMushrooms.setText("Mushroom name cannot be empty.");
            return;
        }
        if (comboBoxMushroomType.getSelectedItem().equals("--choose type--")) {
            lMessageMushrooms.setText("Mushroom type cannot be empty.");
            return;
        }
        if (comboBoxMushroomStartOfOccurence.getSelectedItem().equals("--choose month--")) {
            lMessageMushrooms.setText("Mushroom start of occurence cannot be empty.");
            return;
        }
        if (comboBoxMushroomEndOfOccurence.getSelectedItem().equals("--choose month--")) {
            lMessageMushrooms.setText("Mushroom end of occurence cannot be empty.");
            return;
        }
        
        if (tblMushroom.getSelectedRow() == -1) {
            if (tblMushroom.getRowCount() == 0) {
                lMessageMushrooms.setText("There are no mushrooms to be updated.");
            } else {
                lMessageMushrooms.setText("Please select single mushroom.");
            }
        } else {
            mushroomUpdateSwingWorker = new MushroomUpdateSwingWorker();
            mushroomUpdateSwingWorker.execute();
        }
    }//GEN-LAST:event_bMushroomUpdateActionPerformed

    private void bMushroomDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMushroomDeleteActionPerformed
        bMushroomDelete.setEnabled(false);
        bMushroomUpdate.setEnabled(false);

        if (tblMushroom.getSelectedRow() == -1) {
            if (tblMushroom.getRowCount() == 0) {
                lMessageMushrooms.setText("There are no mushrooms to be deleted.");
            } else {
                lMessageMushrooms.setText("Please select single mushroom.");
            }
        } else {
            mushroomDeleteSwingWorker = new MushroomDeleteSwingWorker();
            mushroomDeleteSwingWorker.execute();
        }
    }//GEN-LAST:event_bMushroomDeleteActionPerformed

    private void tblMushroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMushroomMouseClicked
        bMushroomDelete.setEnabled(true);
        bMushroomUpdate.setEnabled(true);

        DefaultTableModel model = (DefaultTableModel) tblMushroom.getModel();
        tfMushroomName.setText(model.getValueAt(tblMushroom.getSelectedRow(), 0).toString());
        comboBoxMushroomType.setSelectedItem(model.getValueAt(tblMushroom.getSelectedRow(), 1).toString());
        comboBoxMushroomStartOfOccurence.setSelectedItem(model.getValueAt(tblMushroom.getSelectedRow(), 2).toString());
        comboBoxMushroomEndOfOccurence.setSelectedItem(model.getValueAt(tblMushroom.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tblMushroomMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RestClient().setVisible(true);
            }
        });
    }

    private static List<Long> locationIDs = new ArrayList<>();

    private LocationCreateSwingWorker locationCreateSwingWorker;

    private class LocationCreateSwingWorker extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            LocationDto locationDto = new LocationDto();
            locationDto.setName(tfLocationName.getText());
            locationDto.setDescription(tfLocationDescription.getText());
            locationDto.setNearCity(tfLocationNearCity.getText());

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            List<MediaType> mediaTypeList = new ArrayList<MediaType>();
            mediaTypeList.add(MediaType.ALL);
            headers.setAccept(mediaTypeList);

            ObjectWriter ow = new ObjectMapper().writer().withDefaultPrettyPrinter();
            String json = ow.writeValueAsString(locationDto);
            HttpEntity request = new HttpEntity(json, headers);

            RestTemplate restTemplate = new RestTemplate();
            Long[] result = restTemplate.postForObject("http://localhost:8080/pa165/rest/location", request, Long[].class);

            locationIDs.add(result[0]);
            return null;
        }

        @Override
        protected void done() {
            DefaultTableModel model = (DefaultTableModel) tblLocation.getModel();
            model.addRow(new Object[]{tfLocationName.getText(), tfLocationDescription.getText(), tfLocationNearCity.getText()});
        }
    }

    private LocationUpdateSwingWorker locationUpdateSwingWorker;

    private class LocationUpdateSwingWorker extends SwingWorker<Integer, Void> {

        @Override
        protected Integer doInBackground() throws Exception {
            DefaultTableModel model = (DefaultTableModel) tblLocation.getModel();
            int selectedRow = tblLocation.getSelectedRow();

            LocationDto locationDto = getLocationDetail(locationIDs.get(selectedRow));
            locationDto.setName(tfLocationName.getText());
            locationDto.setDescription(tfLocationDescription.getText());
            locationDto.setNearCity(tfLocationNearCity.getText());

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            List<MediaType> mediaTypeList = new ArrayList<MediaType>();
            mediaTypeList.add(MediaType.APPLICATION_JSON);
            headers.setAccept(mediaTypeList);

            ObjectWriter ow = new ObjectMapper().writer().withDefaultPrettyPrinter();
            String json = ow.writeValueAsString(locationDto);
            HttpEntity request = new HttpEntity(json, headers);

            RestTemplate restTemplate = new RestTemplate();
            ResponseEntity<LocationDto> newlocation = restTemplate.exchange("http://localhost:8080/pa165/rest/location", HttpMethod.PUT, request, LocationDto.class);
            LocationDto updatedLocation = newlocation.getBody();
            return selectedRow;
        }

        @Override
        protected void done() {
            DefaultTableModel model = (DefaultTableModel) tblLocation.getModel();
            try {
                model.setValueAt(tfLocationName.getText(), get(), 0);
                model.setValueAt(tfLocationDescription.getText(), get(), 1);
                model.setValueAt(tfLocationNearCity.getText(), get(), 2);
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (ExecutionException e) {
                e.printStackTrace();
            }
        }
    }

    private LocationDeleteSwingWorker locationDeleteSwingWorker;

    private class LocationDeleteSwingWorker extends SwingWorker<Integer, Void> {

        protected Integer doInBackground() throws Exception {
            int selectedRow = tblLocation.getSelectedRow();
            RestTemplate restTemplate = new RestTemplate();
            restTemplate.delete("http://localhost:8080/pa165/rest/location/" + locationIDs.get(selectedRow));
            locationIDs.remove(selectedRow);
            return selectedRow;
        }

        protected void done() {
            DefaultTableModel model = (DefaultTableModel) tblLocation.getModel();
            try {
                model.removeRow(get());
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (ExecutionException e) {
                e.printStackTrace();
            }
        }
    }

    private AllLocationsSwingWorker allLocationsSwingWorker;

    private class AllLocationsSwingWorker extends SwingWorker<List<LocationDto>, Void> {

        @Override
        protected List<LocationDto> doInBackground() throws Exception {
            return getLocationList();
        }

        @Override
        protected void done() {
            try {
                List<LocationDto> list = get();
                DefaultTableModel model = (DefaultTableModel) tblLocation.getModel();
                model.setRowCount(0);
                for (int i = 0; i < list.size(); i++) {
                    locationIDs.add(list.get(i).getId());
                    model.addRow(new Object[]{list.get(i).getName(), list.get(i).getDescription(), list.get(i).getNearCity()});
                }
            } catch (ExecutionException ex) {

            } catch (InterruptedException ex) {
                throw new RuntimeException("Operation interrupted", ex);
            }
        }
    }

    private LocationDto getLocationDetail(Long locationId) throws RestClientException {
        RestTemplate restTemplate = new RestTemplate();
        LocationDto location = restTemplate.getForObject("http://localhost:8080/pa165/rest/location/" + locationId, LocationDto.class);
        return location;
    }

    //Send GET to URL and get array of objects
    private List<LocationDto> getLocationList() throws RestClientException {
        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<LocationDto[]> responseEntity = restTemplate.getForEntity("http://localhost:8080/pa165/rest/location/", LocationDto[].class);
        LocationDto[] locationDtoArray = responseEntity.getBody();
        List<LocationDto> locationDtoList = new ArrayList<>();
        locationDtoList.addAll(Arrays.asList(locationDtoArray));
        return locationDtoList;
    }

    //Send GET to URL and get array of objects
    private void getLocationListWithOccurence() throws RestClientException {
        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<LocationDto[]> responseEntity = restTemplate.getForEntity("http://localhost:8080/pa165/rest/location/withMushroomOccurence", LocationDto[].class);
        LocationDto[] locationDtoArray = responseEntity.getBody();
        for (int i = 0; i < locationDtoArray.length; i++) {
            LocationDto location = locationDtoArray[0];
            System.out.println("Id:                 " + location.getId());
            System.out.println("Name:               " + location.getName());
            System.out.println("Description:        " + location.getDescription());
            System.out.println("Near city:          " + location.getNearCity());
            System.out.println("Mushroom occurence: " + location.getMushroomOccurence());
        }
    }

    private static List<Long> mushroomIDs = new ArrayList<>();

    private MushroomCreateSwingWorker mushroomCreateSwingWorker;

    private class MushroomCreateSwingWorker extends SwingWorker<Void, Void> {

        @Override
        protected Void doInBackground() throws Exception {
            MushroomDto mushroomDto = new MushroomDto();
            mushroomDto.setName(tfMushroomName.getText());
            
            mushroomDto.setType(cz.fi.muni.pa165.mushroomhunter.api.Type.valueOf(comboBoxMushroomType.getSelectedItem().toString()));

            //to create date object only month is used, day and year are fixed values
            String dateInString = comboBoxMushroomStartOfOccurence.getSelectedItem().toString() + " 1, 2000";

            SimpleDateFormat formatter = new SimpleDateFormat("MMMM d, yyyy", new Locale("en_US"));

            mushroomDto.setStartOfOccurence(formatter.parse(dateInString));

            //to create date object only month is used, day and year are fixed values
            dateInString = comboBoxMushroomEndOfOccurence.getSelectedItem().toString() + " 1, 2000";
            mushroomDto.setEndOfOccurence(formatter.parse(dateInString));

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            List<MediaType> mediaTypeList = new ArrayList<>();
            mediaTypeList.add(MediaType.ALL);
            headers.setAccept(mediaTypeList);

            ObjectWriter ow = new ObjectMapper().writer().withDefaultPrettyPrinter();
            String json = ow.writeValueAsString(mushroomDto);
            HttpEntity request = new HttpEntity(json, headers);

            RestTemplate restTemplate = new RestTemplate();
            Long[] result = restTemplate.postForObject("http://localhost:8080/pa165/rest/mushroom", request, Long[].class);

            System.out.println("Id of the created mushroom: " + result[0]);
            mushroomIDs.add(result[0]);
            return null;
        }

        @Override
        protected void done() {
            DefaultTableModel model = (DefaultTableModel) tblMushroom.getModel();
            model.addRow(new Object[]{tfMushroomName.getText(), comboBoxMushroomType.getSelectedItem().toString(), comboBoxMushroomStartOfOccurence.getSelectedItem().toString(), comboBoxMushroomEndOfOccurence.getSelectedItem().toString()});
        }
    }

    private MushroomUpdateSwingWorker mushroomUpdateSwingWorker;

    private class MushroomUpdateSwingWorker extends SwingWorker<Integer, Void> {

        @Override
        protected Integer doInBackground() throws Exception {
            DefaultTableModel model = (DefaultTableModel) tblMushroom.getModel();
            int selectedRow = tblMushroom.getSelectedRow();

            MushroomDto mushroomDto = getMushroomDetail(mushroomIDs.get(selectedRow));
            mushroomDto.setName(tfMushroomName.getText());

            SimpleDateFormat formatter = new SimpleDateFormat("dd-MMMM-yyyy", new Locale("en_US"));

            //to create date object only month is used, day and year are fixed values
            String dateInString = "01-" + comboBoxMushroomStartOfOccurence.getSelectedItem().toString() + "-2000";
            mushroomDto.setStartOfOccurence(formatter.parse(dateInString));

            //to create date object only month is used, day and year are fixed values
            dateInString = "01-" + comboBoxMushroomEndOfOccurence.getSelectedItem().toString() + "-2000";
            mushroomDto.setEndOfOccurence(formatter.parse(dateInString));

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            List<MediaType> mediaTypeList = new ArrayList<MediaType>();
            mediaTypeList.add(MediaType.APPLICATION_JSON);
            headers.setAccept(mediaTypeList);

            ObjectWriter ow = new ObjectMapper().writer().withDefaultPrettyPrinter();
            String json = ow.writeValueAsString(mushroomDto);
            HttpEntity request = new HttpEntity(json, headers);

            RestTemplate restTemplate = new RestTemplate();
            ResponseEntity<MushroomDto> newmushroom = restTemplate.exchange("http://localhost:8080/pa165/rest/mushroom", HttpMethod.PUT, request, MushroomDto.class);
            MushroomDto updatedMushroom = newmushroom.getBody();
            return selectedRow;
        }

        @Override
        protected void done() {
            DefaultTableModel model = (DefaultTableModel) tblMushroom.getModel();
            try {
                model.setValueAt(tfMushroomName.getText(), get(), 0);
                model.setValueAt(comboBoxMushroomType.getSelectedItem().toString(), get(), 1);
                model.setValueAt(comboBoxMushroomStartOfOccurence.getSelectedItem().toString(), get(), 2);
                model.setValueAt(comboBoxMushroomEndOfOccurence.getSelectedItem().toString(), get(), 3);
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (ExecutionException e) {
                e.printStackTrace();
            }
        }
    }

    private MushroomDeleteSwingWorker mushroomDeleteSwingWorker;

    private class MushroomDeleteSwingWorker extends SwingWorker<Integer, Void> {

        protected Integer doInBackground() throws Exception {
            int selectedRow = tblMushroom.getSelectedRow();
            RestTemplate restTemplate = new RestTemplate();
            restTemplate.delete("http://localhost:8080/pa165/rest/mushroom/" + mushroomIDs.get(selectedRow));
            mushroomIDs.remove(selectedRow);
            return selectedRow;
        }

        protected void done() {
            DefaultTableModel model = (DefaultTableModel) tblMushroom.getModel();
            try {
                model.removeRow(get());
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (ExecutionException e) {
                e.printStackTrace();
            }
        }
    }

    private AllMushroomsSwingWorker allMushroomsSwingWorker;

    private class AllMushroomsSwingWorker extends SwingWorker<List<MushroomDto>, Void> {

        @Override
        protected List<MushroomDto> doInBackground() throws Exception {
            return getMushroomList();
        }

        @Override
        protected void done() {
            try {
                List<MushroomDto> list = get();
                DefaultTableModel model = (DefaultTableModel) tblMushroom.getModel();
                model.setRowCount(0);
                for (int i = 0; i < list.size(); i++) {
                    mushroomIDs.add(list.get(i).getId());

                    SimpleDateFormat MMMMFormat = new SimpleDateFormat("MMMM", new Locale("en_US"));
                    String startOfOccurence = MMMMFormat.format(list.get(i).getStartOfOccurence());
                    String endOfOccurence = MMMMFormat.format(list.get(i).getEndOfOccurence());

                    model.addRow(new Object[]{list.get(i).getName(), list.get(i).getType().toString(), startOfOccurence, endOfOccurence});
                }
            } catch (ExecutionException ex) {

            } catch (InterruptedException ex) {
                throw new RuntimeException("Operation interrupted", ex);
            }
        }
    }

    private MushroomDto getMushroomDetail(Long mushroomId) throws RestClientException {
        RestTemplate restTemplate = new RestTemplate();
        MushroomDto mushroom = restTemplate.getForObject("http://localhost:8080/pa165/rest/mushroom/" + mushroomId, MushroomDto.class);
        return mushroom;
    }

    //Send GET to URL and get array of objects
    private List<MushroomDto> getMushroomList() throws RestClientException {
        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<MushroomDto[]> responseEntity = restTemplate.getForEntity("http://localhost:8080/pa165/rest/mushroom/", MushroomDto[].class);
        MushroomDto[] mushroomDtoArray = responseEntity.getBody();
        List<MushroomDto> mushroomDtoList = new ArrayList<>();
        mushroomDtoList.addAll(Arrays.asList(mushroomDtoArray));
        return mushroomDtoList;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLocationCreate;
    private javax.swing.JButton bLocationDelete;
    private javax.swing.JButton bLocationUpdate;
    private javax.swing.JButton bMushroomCreate;
    private javax.swing.JButton bMushroomDelete;
    private javax.swing.JButton bMushroomUpdate;
    private javax.swing.JComboBox comboBoxMushroomEndOfOccurence;
    private javax.swing.JComboBox comboBoxMushroomStartOfOccurence;
    private javax.swing.JComboBox comboBoxMushroomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lMessageLocations;
    private javax.swing.JLabel lMessageMushrooms;
    private javax.swing.JTable tblLocation;
    private javax.swing.JTable tblMushroom;
    private javax.swing.JTextField tfLocationDescription;
    private javax.swing.JTextField tfLocationName;
    private javax.swing.JTextField tfLocationNearCity;
    private javax.swing.JTextField tfMushroomName;
    // End of variables declaration//GEN-END:variables
}
